version: '3.8'

services:
  # 1. The Frontend (React/Vite)
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - answering-agent

  # 2. The Answering Agent (FastAPI)
  answering-agent:
    build: 
      context: ./backend
    # This runs your main.py (FastAPI)
    command: gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:7860
    ports:
      - "8000:7860"
    env_file: ./backend/.env

  # 3. The Ingestion Agent (Streamlit)
  ingestion-agent:
    build: 
      context: ./backend
    # This tells the SAME image to run the Streamlit dashboard instead
    command: streamlit run data_ingestion/app.py --server.port 7860 --server.address 0.0.0.0
    ports:
      - "8501:7860"
    env_file: ./backend/.env