import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const MessageBubble = ({ role, content }) => {
  const isUser = role === 'user';

  // Integrated CSS Styles
  const styles = {
    wrapper: {
      display: 'flex',
      justifyContent: isUser ? 'flex-end' : 'flex-start',
      margin: '10px 0',
      width: '100%',
    },
    bubble: {
      maxWidth: '75%',
      padding: '12px 16px',
      borderRadius: '15px',
      fontSize: '14px',
      lineHeight: '1.5',
      backgroundColor: isUser ? '#dc143c' : '#f0f2f5', // Fino Crimson for user, Light Gray for AI
      color: isUser ? '#ffffff' : '#1a1a1a',
      boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
      borderBottomRightRadius: isUser ? '2px' : '15px',
      borderBottomLeftRadius: isUser ? '15px' : '2px',
    },
    markdown: {
      // These rules target the HTML tags generated by ReactMarkdown
      fontSize: '14px',
      overflowX: 'auto',
    }
  };

  return (
    <div style={styles.wrapper}>
      <div style={styles.bubble}>
        {isUser ? (
          <p style={{ margin: 0 }}>{content}</p>
        ) : (
          <div className="markdown-content" style={styles.markdown}>
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {content}
            </ReactMarkdown>

            {/* Direct CSS Injection for Markdown Elements */}
            <style dangerouslySetInnerHTML={{
              __html: `
              .markdown-content h3 { font-size: 1.1rem; margin: 10px 0 5px 0; color: #b3002d; }
              .markdown-content p { margin: 0 0 10px 0; }
              .markdown-content ul { padding-left: 20px; margin-bottom: 10px; }
              .markdown-content li { margin-bottom: 4px; }
              .markdown-content table { border-collapse: collapse; width: 100%; margin: 10px 0; font-size: 12px; }
              .markdown-content th, .markdown-content td { border: 1px solid #ccc; padding: 6px; text-align: left; }
              .markdown-content th { background-color: #eee; }
              .markdown-content strong { color: #b3002d; } /* Highlights key Fino terms */
            `}} />
          </div>
        )}
      </div>
    </div>
  );
};

export default MessageBubble;